name: Reinforce Code Standards
on:
  push:
    branches:
      - main
      - develop
jobs:
  reinforce-code-standards:
    name: Reinforce Code Standards
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18
    steps:
      - name: Download repository
        uses: actions/checkout@v3
      - name: 'Install node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: 'npm runt lint:fix && style:fix'
      - name: Run unit tests
        run: npm test
